/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Activity
         * @description What's happened lately in the matters the caller can see, newest first.
         */
        get: operations["list_activity_activity_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat-models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Chat Models */
        get: operations["list_chat_models_chat_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Documents */
        get: operations["list_documents_documents_get"];
        put?: never;
        /** Upload Document */
        post: operations["upload_document_documents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/duplicates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Find Duplicates
         * @description Which of these files the caller can already see a copy of.
         *
         *     Asked before uploading, so a file dropped a second time can be caught
         *     and the person asked whether they meant to. Only documents the caller
         *     can see count, a copy in a matter they're not on isn't theirs to be
         *     told about. The earliest copy of each is the one returned.
         */
        post: operations["find_duplicates_documents_duplicates_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Document */
        get: operations["get_document_documents__document_id__get"];
        put?: never;
        post?: never;
        /** Delete Document */
        delete: operations["delete_document_documents__document_id__delete"];
        options?: never;
        head?: never;
        /**
         * Rename Document
         * @description Rename a document, keeping its extension.
         *
         *     409 if another document in the same matter already has the name, so the
         *     person can pick another rather than get a "(2)" they didn't ask for.
         */
        patch: operations["rename_document_documents__document_id__patch"];
        trace?: never;
    };
    "/documents/{document_id}/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Document File
         * @description The file as it was uploaded, for the viewer and for downloading.
         *
         *     Inline by default so the browser can show it, `?download=true` asks for
         *     an attachment instead. Under the original filename either way, rather
         *     than the uuid it's stored under. A row whose file has gone from storage 404s
         *     with its own message, since that's a storage problem and not a document
         *     the caller can't see.
         *
         *     Passed through the api rather than redirecting to a presigned bucket url,
         *     so the file stays behind the same sign in as everything else and the
         *     browser never needs the bucket to answer it cross origin.
         */
        get: operations["get_document_file_documents__document_id__file_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{document_id}/passages/{chunk_index}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Passage
         * @description One passage of a document, what a citation in an answer points at.
         *
         *     Checked against the document's own visibility first, so a passage of a
         *     document the caller can't see 404s the same way the document does.
         */
        get: operations["get_passage_documents__document_id__passages__chunk_index__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/intakes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Intake */
        post: operations["create_intake_intakes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/intakes/{intake_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Intake */
        get: operations["get_intake_intakes__intake_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/intakes/{intake_id}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Intake Document */
        post: operations["add_intake_document_intakes__intake_id__documents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/intakes/{intake_id}/seal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Seal Intake */
        post: operations["seal_intake_intakes__intake_id__seal_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/press": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Firm Press
         * @description Press across every matter the caller belongs to, newest added first.
         */
        get: operations["list_firm_press_press_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/press/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Preview Press Link
         * @description What a pasted link's page says about itself, before anything is saved.
         */
        post: operations["preview_press_link_press_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/press/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Press Sources
         * @description Firm wide sources, plus one matter's own when `project` names it.
         */
        get: operations["list_press_sources_press_sources_get"];
        put?: never;
        /** Add Press Source */
        post: operations["add_press_source_press_sources_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/press/sources/{source_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Press Source
         * @description Remove a source. What it already found stays.
         */
        delete: operations["delete_press_source_press_sources__source_id__delete"];
        options?: never;
        head?: never;
        /** Update Press Source */
        patch: operations["update_press_source_press_sources__source_id__patch"];
        trace?: never;
    };
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projects */
        get: operations["list_projects_projects_get"];
        put?: never;
        /** Create Project */
        post: operations["create_project_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Member */
        post: operations["add_member_projects__project_id__members_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_ref}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project */
        get: operations["get_project_projects__project_ref__get"];
        put?: never;
        post?: never;
        /**
         * Delete Project
         * @description Delete a matter along with every document in it.
         *
         *     Documents don't cascade from their matter on purpose, see the note on
         *     Document in app/models.py, so they go first by hand. Their chunks,
         *     metadata and profiles cascade from them, and the matter's parties, dates,
         *     members, pins and views cascade from it. The audit log keeps its entries,
         *     it's the record that any of this happened.
         */
        delete: operations["delete_project_projects__project_ref__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_ref}/pin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Pin Project */
        put: operations["pin_project_projects__project_ref__pin_put"];
        post?: never;
        /** Unpin Project */
        delete: operations["unpin_project_projects__project_ref__pin_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_ref}/press": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Project Press */
        get: operations["list_project_press_projects__project_ref__press_get"];
        put?: never;
        /**
         * Add Press Link
         * @description Put a pasted article on a matter. Kept straight away, someone chose it.
         */
        post: operations["add_press_link_projects__project_ref__press_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_ref}/press/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh Project Press
         * @description Search now. Every source this matter uses is read or searched after the
         *     response goes, a first search back to the matter's earliest date takes
         *     minutes. The sources' search status says how it's going.
         */
        post: operations["refresh_project_press_projects__project_ref__press_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_ref}/press/terms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Press Terms */
        get: operations["get_press_terms_projects__project_ref__press_terms_get"];
        /**
         * Set Press Terms
         * @description Replace a matter's terms. An empty watch list goes back to the parties.
         *
         *     Different terms find different articles, so the matter's outlet searches
         *     start again from its earliest date. What they found before stays.
         */
        put: operations["set_press_terms_projects__project_ref__press_terms_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_ref}/press/{mention_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Press Mention */
        patch: operations["update_press_mention_projects__project_ref__press__mention_id__patch"];
        trace?: never;
    };
    "/projects/{project_ref}/press/{outlet_slug}/{article_slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Press Article */
        get: operations["get_press_article_projects__project_ref__press__outlet_slug___article_slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_ref}/view": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Record View */
        put: operations["record_view_projects__project_ref__view_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/queries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Queries
         * @description A caller's own past questions and their answers, newest first.
         *
         *     Only the asker's own. A question someone asked is theirs, not news for
         *     the rest of the matter, which is also why the activity feed leaves
         *     queries out, see app/activity.py.
         */
        get: operations["list_queries_queries_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Query */
        post: operations["query_query_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users */
        get: operations["list_users_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Me */
        get: operations["get_me_users_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me/job-title": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set My Job Title */
        put: operations["set_my_job_title_users_me_job_title_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me/model": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get My Model */
        get: operations["get_my_model_users_me_model_get"];
        /** Set My Model */
        put: operations["set_my_model_users_me_model_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get My Preferences */
        get: operations["get_my_preferences_users_me_preferences_get"];
        /** Set My Preferences */
        put: operations["set_my_preferences_users_me_preferences_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me/recently-viewed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Recently Viewed
         * @description The caller's most recently opened matters, newest first.
         *
         *     As many as their `recently_viewed_count` setting asks for. A matter
         *     they've since been taken off or that's no longer listed drops out.
         */
        get: operations["list_recently_viewed_users_me_recently_viewed_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Deactivate User */
        patch: operations["deactivate_user_users__user_id__patch"];
        trace?: never;
    };
    "/users/{user_id}/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Change Role */
        patch: operations["change_role_users__user_id__role_patch"];
        trace?: never;
    };
    "/webhooks/clerk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Clerk Webhook */
        post: operations["clerk_webhook_webhooks_clerk_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActivityDocumentOut */
        ActivityDocumentOut: {
            /** Exists */
            exists: boolean;
            /** Filename */
            filename: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
        };
        /** ActivityMatterOut */
        ActivityMatterOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
        };
        /** ActivityOut */
        ActivityOut: {
            /** Action */
            action: string;
            actor: components["schemas"]["ActorOut"] | null;
            /** Count */
            count: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            document: components["schemas"]["ActivityDocumentOut"] | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            matter: components["schemas"]["ActivityMatterOut"] | null;
            /** Pages */
            pages: number | null;
        };
        /** ActorOut */
        ActorOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
        };
        /** Body_add_intake_document_intakes__intake_id__documents_post */
        Body_add_intake_document_intakes__intake_id__documents_post: {
            /** File */
            file: string;
        };
        /** Body_upload_document_documents_post */
        Body_upload_document_documents_post: {
            /** File */
            file: string;
            /** Project Id */
            project_id?: string | null;
        };
        /** CaseMetadataOut */
        CaseMetadataOut: {
            /** Case Date */
            case_date: string | null;
            /** Court */
            court: string | null;
            /**
             * Extracted At
             * Format: date-time
             */
            extracted_at: string;
            /** Location */
            location: string | null;
            /** Needs Review */
            needs_review: boolean;
            /** Offence Text */
            offence_text: string | null;
            /** Offence Type */
            offence_type: string | null;
            /** Review Reason */
            review_reason: string | null;
            /** Sentence Months */
            sentence_months: number | null;
            /** Sentence Text */
            sentence_text: string | null;
            /** Sentence Type */
            sentence_type: string | null;
        };
        /** ChatModelOut */
        ChatModelOut: {
            /** Id */
            id: string;
            /** Is Default */
            is_default: boolean;
            /** Label */
            label: string;
            /**
             * Provider
             * @enum {string}
             */
            provider: "openai" | "anthropic";
        };
        /** CitationOut */
        CitationOut: {
            /** Chunk Index */
            chunk_index: number | null;
            /**
             * Document Id
             * Format: uuid
             */
            document_id: string;
            /** Filename */
            filename: string;
            /** Number */
            number: number;
            /** Page End */
            page_end: number | null;
            /** Page Start */
            page_start: number | null;
            /** Project Id */
            project_id: string | null;
            /** Project Name */
            project_name: string | null;
            /** Project Slug */
            project_slug: string | null;
            /** Text */
            text: string;
        };
        /** CounselOut */
        CounselOut: {
            /** Acting For */
            acting_for: string | null;
            /** Name */
            name: string;
        };
        /** DateOut */
        DateOut: {
            /** Label */
            label: string;
            /**
             * On Date
             * Format: date
             */
            on_date: string;
            /** Source Document Id */
            source_document_id: string | null;
        };
        /** DocumentDetailOut */
        DocumentDetailOut: {
            case_metadata: components["schemas"]["CaseMetadataOut"] | null;
            /** Error Message */
            error_message: string | null;
            /** Filename */
            filename: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Ingestion Stage */
            ingestion_stage: string | null;
            /** Project Id */
            project_id: string | null;
            /** Status */
            status: string;
            /**
             * Uploaded At
             * Format: date-time
             */
            uploaded_at: string;
        };
        /** DocumentOut */
        DocumentOut: {
            /** Error Message */
            error_message: string | null;
            /** Filename */
            filename: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Ingestion Stage */
            ingestion_stage: string | null;
            /** Project Id */
            project_id: string | null;
            /** Status */
            status: string;
            /**
             * Uploaded At
             * Format: date-time
             */
            uploaded_at: string;
        };
        /** DocumentRename */
        DocumentRename: {
            /** Name */
            name: string;
        };
        /** DuplicateCheck */
        DuplicateCheck: {
            /** Sha256 */
            sha256: string[];
        };
        /** DuplicateMatterOut */
        DuplicateMatterOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
        };
        /** DuplicateOut */
        DuplicateOut: {
            /**
             * Document Id
             * Format: uuid
             */
            document_id: string;
            /** Filename */
            filename: string;
            matter: components["schemas"]["DuplicateMatterOut"] | null;
            /** Sha256 */
            sha256: string;
            /**
             * Uploaded At
             * Format: date-time
             */
            uploaded_at: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /** Status */
            status: string;
        };
        /** IntakeMatterOut */
        IntakeMatterOut: {
            /** Document Ids */
            document_ids: string[];
            /** Is New */
            is_new: boolean;
            matter: components["schemas"]["ProjectOut"];
        };
        /** IntakeOut */
        IntakeOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Documents */
            documents: components["schemas"]["DocumentOut"][];
            /** Error Message */
            error_message: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Matters */
            matters: components["schemas"]["IntakeMatterOut"][];
            /** Status */
            status: string;
        };
        /** JobTitle */
        JobTitle: {
            /** Job Title */
            job_title?: string | null;
        };
        /** MemberAdd */
        MemberAdd: {
            /**
             * Access Level
             * @default member
             */
            access_level: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
        };
        /** MentionUpdate */
        MentionUpdate: {
            /**
             * Status
             * @enum {string}
             */
            status: "new" | "kept" | "dismissed";
        };
        /** ModelChoice */
        ModelChoice: {
            /** Model */
            model: string;
        };
        /** PagePreviewOut */
        PagePreviewOut: {
            /** Description */
            description: string | null;
            /** Image Url */
            image_url: string | null;
            /** Published At */
            published_at: string | null;
            /** Site Name */
            site_name: string;
            /** Title */
            title: string;
            /** Url */
            url: string;
        };
        /** PartyOut */
        PartyOut: {
            /** Is Client */
            is_client: boolean;
            /** Name */
            name: string;
            /** Role */
            role: string | null;
        };
        /** PassageOut */
        PassageOut: {
            /** Chunk Index */
            chunk_index: number;
            /** Page End */
            page_end: number | null;
            /** Page Start */
            page_start: number | null;
            /** Text */
            text: string;
        };
        /** Preferences */
        Preferences: {
            /**
             * Recently Viewed Count
             * @enum {integer}
             */
            recently_viewed_count: 3 | 8;
            /** Show Recently Viewed */
            show_recently_viewed: boolean;
        };
        /** PressArticleOut */
        PressArticleOut: {
            /** Excerpt */
            excerpt: string | null;
            /**
             * Fetched At
             * Format: date-time
             */
            fetched_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Image Url */
            image_url: string | null;
            /** Outlet Name */
            outlet_name: string;
            /** Outlet Slug */
            outlet_slug: string;
            /** Published At */
            published_at: string | null;
            /** Slug */
            slug: string;
            /** Source Name */
            source_name: string | null;
            /** Title */
            title: string;
            /** Url */
            url: string;
        };
        /** PressLink */
        PressLink: {
            /** Url */
            url: string;
        };
        /** PressMentionOut */
        PressMentionOut: {
            /** Added By Hand */
            added_by_hand: boolean;
            article: components["schemas"]["PressArticleOut"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Matched Terms */
            matched_terms: string[];
            project: components["schemas"]["PressProjectOut"];
            /** Status */
            status: string;
        };
        /** PressProjectOut */
        PressProjectOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
        };
        /** PressRefreshOut */
        PressRefreshOut: {
            /** Searches Started */
            searches_started: number;
        };
        /** PressSearchOut */
        PressSearchOut: {
            /** Found */
            found: number;
            /** Last Error */
            last_error: string | null;
            /** Searched From */
            searched_from: string | null;
            /** Searched To */
            searched_to: string | null;
            /** Status */
            status: string;
        };
        /** PressSourceCreate */
        PressSourceCreate: {
            /** Category */
            category?: string | null;
            /** Domain */
            domain?: string | null;
            /**
             * Kind
             * @default site
             * @enum {string}
             */
            kind: "site" | "google_news" | "rss";
            /** Name */
            name: string;
            /** Project */
            project?: string | null;
            /** Url */
            url?: string | null;
        };
        /** PressSourceOut */
        PressSourceOut: {
            /** Article Count */
            article_count: number;
            /** Category */
            category: string | null;
            /** Domain */
            domain: string | null;
            /** Enabled */
            enabled: boolean;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Kind */
            kind: string;
            /** Last Error */
            last_error: string | null;
            /** Last Fetched At */
            last_fetched_at: string | null;
            /** Name */
            name: string;
            /** Project Id */
            project_id: string | null;
            search?: components["schemas"]["PressSearchOut"] | null;
            /**
             * Searching
             * @default false
             */
            searching: boolean;
            /** Slug */
            slug: string;
            /** Url */
            url: string | null;
        };
        /** PressSourceUpdate */
        PressSourceUpdate: {
            /** Category */
            category?: string | null;
            /** Enabled */
            enabled?: boolean | null;
            /** Name */
            name?: string | null;
        };
        /** PressTerms */
        PressTerms: {
            /** Exclude */
            exclude: string[];
            /** Require */
            require: string[];
            /** Watch */
            watch: string[];
        };
        /** PressTermsOut */
        PressTermsOut: {
            /** Exclude */
            exclude: string[];
            /** Require */
            require: string[];
            /** Watch */
            watch: string[];
            /** Watch Is Default */
            watch_is_default: boolean;
        };
        /** ProjectCreate */
        ProjectCreate: {
            /** Client Reference */
            client_reference?: string | null;
            /** Name */
            name: string;
            /** Practice Area */
            practice_area?: ("Crime" | "Civil litigation" | "Commercial" | "Employment" | "Family" | "Personal injury" | "Property" | "Immigration" | "Private client" | "Regulatory") | null;
        };
        /** ProjectMemberOut */
        ProjectMemberOut: {
            /** Access Level */
            access_level: string;
            /**
             * Added At
             * Format: date-time
             */
            added_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
        };
        /** ProjectOut */
        ProjectOut: {
            /** Case Reference */
            case_reference: string | null;
            /** Client Reference */
            client_reference: string | null;
            /** Counsel */
            counsel: components["schemas"]["CounselOut"][];
            /** Court */
            court: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Dates */
            dates: components["schemas"]["DateOut"][];
            /** Document Count */
            document_count: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Our Side */
            our_side: string | null;
            /** Parties */
            parties: components["schemas"]["PartyOut"][];
            /** Pinned */
            pinned: boolean;
            /** Practice Area */
            practice_area: string | null;
            /** Press Count */
            press_count: number;
            /** Slug */
            slug: string;
            /** Status */
            status: string;
            /** Summary */
            summary: string | null;
            /** Tags */
            tags: string[];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** QueryHistoryOut */
        QueryHistoryOut: {
            /** Answer */
            answer: string;
            /** Citations */
            citations: components["schemas"]["CitationOut"][];
            /** Conversation Id */
            conversation_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Flagged */
            flagged: boolean;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Model */
            model: string;
            project: components["schemas"]["QueryHistoryProjectOut"] | null;
            /** Question */
            question: string;
        };
        /** QueryHistoryProjectOut */
        QueryHistoryProjectOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
        };
        /** QueryIn */
        QueryIn: {
            /** Conversation Id */
            conversation_id?: string | null;
            /** Project Id */
            project_id?: string | null;
            /** Question */
            question: string;
        };
        /** QueryOut */
        QueryOut: {
            /** Answer */
            answer: string;
            /** Citations */
            citations: components["schemas"]["CitationOut"][];
            /**
             * Conversation Id
             * Format: uuid
             */
            conversation_id: string;
            /** Flagged */
            flagged: boolean;
            /** Model */
            model: string;
            /** Path */
            path: string;
        };
        /** RecentlyViewedOut */
        RecentlyViewedOut: {
            matter: components["schemas"]["ProjectOut"];
            /**
             * Viewed At
             * Format: date-time
             */
            viewed_at: string;
        };
        /** RoleChange */
        RoleChange: {
            /** Role */
            role: string;
        };
        /** StaffAccount */
        StaffAccount: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Email */
            email: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Active */
            is_active: boolean;
            /** Role */
            role: string;
        };
        /** UserProfile */
        UserProfile: {
            /** Email */
            email: string;
            /**
             * Firm Id
             * Format: uuid
             */
            firm_id: string;
            /** First Name */
            first_name: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Job Title */
            job_title: string | null;
            /** Last Name */
            last_name: string | null;
            /** Role */
            role: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_activity_activity_get: {
        parameters: {
            query?: {
                /** @description a matter's id or slug */
                project?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_chat_models_chat_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatModelOut"][];
                };
            };
        };
    };
    list_documents_documents_get: {
        parameters: {
            query?: {
                status?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_document_documents_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_document_documents_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    find_duplicates_documents_duplicates_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DuplicateCheck"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DuplicateOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_documents__document_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_document_documents__document_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rename_document_documents__document_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DocumentRename"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_file_documents__document_id__file_get: {
        parameters: {
            query?: {
                download?: boolean;
            };
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_passage_documents__document_id__passages__chunk_index__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
                chunk_index: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PassageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    create_intake_intakes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntakeOut"];
                };
            };
        };
    };
    get_intake_intakes__intake_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                intake_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntakeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_intake_document_intakes__intake_id__documents_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                intake_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_add_intake_document_intakes__intake_id__documents_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    seal_intake_intakes__intake_id__seal_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                intake_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntakeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_firm_press_press_get: {
        parameters: {
            query?: {
                include_dismissed?: boolean;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PressMentionOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_press_link_press_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PressLink"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagePreviewOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_press_sources_press_sources_get: {
        parameters: {
            query?: {
                project?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PressSourceOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_press_source_press_sources_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PressSourceCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PressSourceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_press_source_press_sources__source_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_press_source_press_sources__source_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PressSourceUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PressSourceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_projects_projects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"][];
                };
            };
        };
    };
    create_project_projects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_member_projects__project_id__members_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemberAdd"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectMemberOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_projects__project_ref__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_ref: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_project_projects__project_ref__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_ref: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pin_project_projects__project_ref__pin_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_ref: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unpin_project_projects__project_ref__pin_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_ref: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_project_press_projects__project_ref__press_get: {
        parameters: {
            query?: {
                include_dismissed?: boolean;
            };
            header?: never;
            path: {
                project_ref: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PressMentionOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_press_link_projects__project_ref__press_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_ref: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PressLink"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PressMentionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_project_press_projects__project_ref__press_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_ref: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PressRefreshOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_press_terms_projects__project_ref__press_terms_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_ref: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PressTermsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_press_terms_projects__project_ref__press_terms_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_ref: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PressTerms"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PressTermsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_press_mention_projects__project_ref__press__mention_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_ref: string;
                mention_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MentionUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PressMentionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_press_article_projects__project_ref__press__outlet_slug___article_slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_ref: string;
                outlet_slug: string;
                article_slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PressMentionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    record_view_projects__project_ref__view_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_ref: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_queries_queries_get: {
        parameters: {
            query?: {
                /** @description a matter's id or slug */
                project?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryHistoryOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    query_query_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueryIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_users_users_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StaffAccount"][];
                };
            };
        };
    };
    get_me_users_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfile"];
                };
            };
        };
    };
    set_my_job_title_users_me_job_title_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobTitle"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobTitle"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_my_model_users_me_model_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelChoice"];
                };
            };
        };
    };
    set_my_model_users_me_model_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModelChoice"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelChoice"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_my_preferences_users_me_preferences_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Preferences"];
                };
            };
        };
    };
    set_my_preferences_users_me_preferences_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Preferences"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Preferences"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_recently_viewed_users_me_recently_viewed_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecentlyViewedOut"][];
                };
            };
        };
    };
    deactivate_user_users__user_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StaffAccount"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_role_users__user_id__role_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleChange"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StaffAccount"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clerk_webhook_webhooks_clerk_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
